name: Mirror actions
run-name: mirror actions

on:
  push:
  schedule:
    - cron:  '0 */12 * * *' # every 12 hours on the hour
jobs:
  mirrors:
    strategy:
      matrix:
        include:
          - dest: "actions-mirror/checkout"
            source: "actions/checkout"
          - dest: "actions-mirror/stale"
            source: "actions/stale"
          - dest: "actions-mirror/docker-metadata-action"
            source: "docker/metadata-action"
    runs-on: ubuntu-latest
    steps:
      - name: mirror github.com/${{ matrix.source }} to gitee.com/${{ matrix.dest }}
        run: |
          mkdir -p actions docker
          git clone --mirror https://github.com/${{ matrix.source }} ./${{ matrix.source }}
          cd ./${{ matrix.source }}
          git remote add gitee https://oauth2:${{ secrets.ACTIONS_TOKEN }}@gitee.com/${{ matrix.dest }}.git
          git push --mirror gitee
