name: Mirror actions
run-name: mirror actions

on:
  push:
  schedule:
    - cron:  '0 */12 * * *' # every 12 hours on the hour
jobs:
  mirrors:
    strategy:
      fail-fast: false
      matrix:
        include:
          - dest: "actions-mirror-Jireh/checkout"
            source: "actions/checkout"
          - dest: "actions-mirror-Jireh/stale"
            source: "actions/stale"
          - dest: "actions-mirror-Jireh/docker-metadata-action"
            source: "docker/metadata-action"
          - dest: "actions-mirror-Jireh/docker-setup-qemu-action"
            source: "docker/setup-qemu-action"
          - dest: "actions-mirror-Jireh/docker-build-push-action"
            source: "docker/build-push-action"
          - dest: "actions-mirror-Jireh/docker-setup-buildx-action"
            source: "docker/setup-buildx-action"
          - dest: "actions-mirror-Jireh/docker-login-action"
            source: "docker/login-action"
          - dest: "actions-mirror-Jireh/setup-dotnet"
            source: "actions/setup-dotnet"
          - dest: "actions-mirror-Jireh/download-artifact"
            source: "actions/download-artifact"
          - dest: "actions-mirror-Jireh/upload-artifact"
            source: "actions/upload-artifact"
          - dest: "actions-mirror-Jireh/setup-python"
            source: "actions/setup-python"
          - dest: "actions-mirror-Jireh/setup-node"
            source: "actions/setup-node"
          - dest: "actions-mirror-Jireh/setup-go"
            source: "actions/setup-go"
          - dest: "actions-mirror-Jireh/cache"
            source: "actions/cache"
          - dest: "actions-mirror-Jireh/setup-java"
            source: "actions/setup-java"
          - dest: "actions-mirror-Jireh/setup-maven"
            source: "stCarolas/setup-maven"
          - dest: "actions-mirror-Jireh/maven-settings-action"
            source: "s4u/maven-settings-action"
          - dest: "actions-mirror-Jireh/goreleaser-action"
            source: "goreleaser/goreleaser-action"
          - dest: "actions-mirror-Jireh/bot-notice-action"
            source: "hb0730/bot-notice-action"
          - dest: "actions-mirror-Jireh/maven-action"
            source: "hb0730/maven-action"
          - dest: "actions-mirror-Jireh/release-changelog-builder-action"
            source: "mikepenz/release-changelog-builder-action"
          - dest: "actions-mirror-Jireh/gitea-release-action"
            source: "akkuman/gitea-release-action"
          - dest: "actions-mirror-Jireh/action-send-mail"
            source: "dawidd6/action-send-mail"
          - dest: "actions-mirror-Jireh/ssh-action"
            source: "appleboy/ssh-action"
          - dest: "actions-mirror-Jireh/github-action-scp"
            source: "garygrossgarten/github-action-scp"
          - dest: "actions-mirror-Jireh/gitea"
            source: "go-gitea/gitea"
          
    runs-on: ubuntu-latest
    steps:
      - name: mirror github.com/${{ matrix.source }} to gitee.com/${{ matrix.dest }}
        run: |
          git clone --mirror https://github.com/${{ matrix.source }} ./${{ matrix.source }}
          cd ./${{ matrix.source }}
          git remote add gitee https://oauth2:${{ secrets.ACTIONS_TOKEN }}@gitee.com/${{ matrix.dest }}.git
          # https://stackoverflow.com/questions/47776357/git-push-mirror-without-pull-refs
          git show-ref | cut -d' ' -f2 | grep 'pull' | xargs -r -L1 git update-ref -d
          git push -f gitee --mirror


