name: Mirror actions
run-name: mirror actions

on:
  push:
  schedule:
    - cron:  '0 */12 * * *' # every 12 hours on the hour
jobs:
  mirrors:
    strategy:
      matrix:
        include:
           - dest: "actions-mirror/checkout"
             source: "actions/checkout"
    runs-on: ubuntu-latest
    steps:
      - name: mirror github.com/${{ matrix.source }} to gitee.com/${{ matrix.dest }}
        run: |
          git clone --mirror https://github.com/${{ matrix.source }} ./${{ matrix.source }}
          cd ./${{ matrix.source }}
          git remote add cn https://hb0730:${{ secrets.ACTIONS_TOKEN }}@gitee.com/${{ matrix.dest }}.git
          git push --mirror cn
